raspiPOS/urls.py
from django.contrib import admin
from django.urls import path, include
from simorder.admin import custom_admin_site

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('admin/', custom_admin_site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('simorder.urls')),
]

simorder/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='urlHome'),
    path('orders/', views.display_orders, name='urlOrders'),
    path('orders/all', views.display_orders_all, name='urlOrdersAll'),
    path('orders/create/<int:menu_id>', views.create_order, name='urlCreateOrder'),
    path('orders/update/<int:id>', views.update_order, name='urlUpdateOrder'),
    path('orders/close/<int:id>', views.close_order, name='urlCloseOrder'),    
    path('orders/close/<int:id>/<str:poTransNumber>', views.close_order, name='urlReprintOrder'),    
    path('orders/delete/<int:id>', views.delete_order, name='urlDeleteOrder'),
    path('orders/delete/orderproduct/<int:id>', views.delete_order_product, name='urlDeleteOrderProduct'),
    path('orders/admin/all', views.admin_orders_all, name='urlAdminOrdersAll'),
    path('printers/', views.printers_view, name='urlPrinters'),    
    path('settings/', views.settings, name='urlSettings'),    
    path('power/<int:op_id>', views.power, name='urlPower'),
]

simorder/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
import random


class Printer(models.Model):
    printName = models.CharField(max_length=255, verbose_name=_('Printer'), unique=True, null=True)
    printType = models.CharField(max_length=25)
    printIdVendor = models.PositiveIntegerField(null=True)
    printIdProduct = models.PositiveIntegerField(null=True)
    printIn_ep = models.PositiveIntegerField(null=True)
    printOut_ep = models.PositiveIntegerField(null=True)
    printMacAddress = models.CharField(max_length=17, null=True)

    class Meta:
        ordering = ['printName']

    def __str__(self):
        return self.printName


class ProductClass(models.Model):
    classDescription = models.CharField(verbose_name=_('Description'), max_length=255, unique=True)
    classColor = models.CharField(verbose_name=_('Display color'), max_length=7, default='#0d6efd')
    printQuery = models.ForeignKey(Printer, verbose_name=_('Order Printer'), on_delete=models.SET_NULL, blank=True, null=True)
    isActive = models.BooleanField(verbose_name=_('Active?'), default=True)

    class Meta:
        verbose_name = _('Product Class')
        verbose_name_plural = _('Product Classes')

    def __str__(self):
        return self.classDescription


class Product(models.Model):
    prodclassQuery = models.ForeignKey(ProductClass, verbose_name=_('Product Class'), on_delete=models.PROTECT, default=1)
    prodDescription = models.CharField(verbose_name=_('Product'), max_length=255)
    prodStock = models.DecimalField(verbose_name=_('Stock'), max_digits=6, decimal_places=2, default=0.00, validators=[MinValueValidator(0)])
    prodPrice = models.DecimalField(verbose_name=_('Price'), max_digits=6, decimal_places=2, default=0.00, validators=[MinValueValidator(0)])
    prodVAT = models.DecimalField(verbose_name=_('VAT (%)'), max_digits=5, decimal_places=2, default=0.00, validators=[MinValueValidator(0), MaxValueValidator(100)])
    isActive = models.BooleanField(verbose_name=_('Active?'), default=True)

    class Meta:
        ordering = ['prodclassQuery', 'prodDescription']

    def __str__(self):
        return self.prodDescription


class Menu(models.Model):
    menuActive = models.BooleanField(verbose_name=_('Active?'), default=False)
    menuService = models.BooleanField(verbose_name=_('Table Service?'), default=False)
    menuDescription = models.CharField(max_length=255, verbose_name=_('Menu'))
    prodQuery = models.ManyToManyField(Product, verbose_name=_('Product'))
    printQuery = models.ForeignKey(Printer, verbose_name=_('Receipt Printer'), on_delete=models.SET_NULL, blank=True, null=True)
    isActive = models.BooleanField(verbose_name=_('Active?'), default=True)

    class Meta:
        ordering = ['menuDescription']
    
    def __str__(self):
        return self.menuDescription


class Order(models.Model):
    orderUser = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    orderDtOpen = models.DateTimeField(auto_now_add=True)
    orderDtClose = models.DateTimeField(auto_now=True)
    orderStatus = models.IntegerField(default=0, verbose_name=_('Order Status')) #0: open, 1: closed, 2: cancelled/ deleted
    orderTable = models.CharField(max_length=25, verbose_name=_('Table'))
    menuQuery = models.ForeignKey(Menu, on_delete=models.PROTECT, verbose_name=_('Menu'), default=1)
    prodQuery = models.ManyToManyField(Product, through='ProductOrder')
        
    def save_model(self, request, obj, form, change):
        obj.orderuser = request.user
        super().save_model(request, obj, form, change)

    @property
    def get_total_order(self):
        return ProductOrder.get_total_order(self)
    
    @property
    def get_total_closed(self):
        return ProductOrder.get_total_closed(self)


class ProductOrder(models.Model):
    poOrder = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name=_('Order'), default=1)
    poStatus = models.IntegerField(default=0, verbose_name=_('Product Order Status')) #0: open, 1: closed, 2: cancelled/ deleted
    prodQuery = models.ForeignKey(Product, on_delete=models.SET_NULL, verbose_name=_('Product'), default=1, null=True)
    poTransNumber = models.CharField(max_length=20, verbose_name=_('Transaction Number'), blank=True)
    poPayAmount = models.DecimalField(max_digits=6, decimal_places=2, default=0.00)
    poPayMethod = models.CharField(max_length=2, choices=[('CH', _('Cash')), ('DC', _('Debit card')), ('CC', _('Credit card'))], blank=True)
    poDtOpen = models.DateTimeField(auto_now_add=True)
    poDtClose = models.DateTimeField(auto_now=True)

    # Additional fields for hardcopy product information
    poProdDescription = models.CharField(max_length=255)
    poProdPrice = models.DecimalField(max_digits=6, decimal_places=2)
    poProdVAT = models.DecimalField(max_digits=5, decimal_places=2)
    poProdClass = models.CharField(max_length=255)

    def save(self, *args, **kwargs):
            if self.prodQuery and not self.id:
                self.poProdDescription = self.prodQuery.prodDescription
                self.poProdPrice = self.prodQuery.prodPrice
                self.poProdVAT = self.prodQuery.prodVAT
                self.poProdClass = self.prodQuery.prodclassQuery.classDescription
            super().save(*args, **kwargs)

    def generate_transNumber(self):
        while True:
            year = timezone.now().year
            random_number = random.randint(1, 999999999)
            last_two_digits = self.generate_suffix(random_number)
            transaction_number = f"{year}-{random_number:09d}-{last_two_digits:02d}"

            if not ProductOrder.objects.filter(poTransNumber=transaction_number).exists():
                return transaction_number

    def generate_suffix(self, random_number):
        return sum(int(digit) for digit in str(random_number)) % 100
    
    @classmethod
    def get_total_order(cls, order):
        return cls.objects.filter(poOrder=order).exclude(poStatus=2).aggregate(total=models.Sum('poProdPrice'))['total'] or 0

    @classmethod
    def get_total_closed(cls, order):
        return cls.objects.filter(poOrder=order, poStatus=1).aggregate(total=models.Sum('poProdPrice'))['total'] or 0

class SingletonModel(models.Model):
    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        self.pk = 1
        super().save(*args, **kwargs)

    @classmethod
    def load(cls):
        obj, _ = cls.objects.get_or_create(pk=1)
        return obj


class SystemSettings(SingletonModel):
    companyName = models.CharField(max_length=255, verbose_name=_('Company Name'), blank=True)
    companyAdress1 = models.CharField(max_length=255, verbose_name=_('Address'), blank=True)
    companyAdress2 = models.CharField(max_length=255, verbose_name=_('Zip, City'), blank=True)
    companyInfo1 = models.CharField(max_length=255, verbose_name=_('Add. Information 1'), blank=True)
    companyInfo2 = models.CharField(max_length=255, verbose_name=_('Add. Information 2'), blank=True)
    taxIdNumber = models.CharField(max_length=255, verbose_name=_('Tax Number'), blank=True)
    emailHost = models.CharField(max_length=255, verbose_name=_('Email Host'), blank=True)
    emailUser = models.CharField(max_length=255, verbose_name=_('Email User'), blank=True)
    emailPassword = models.CharField(max_length=255, verbose_name=_('Password'), blank=True)

    def __str__(self):
        return "System Settings"

simorder/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load i18n static custom_tags %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
  <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>{% block title %}{% endblock %}</title>
  <style type="text/css">
    a[aria-expanded=true] .fa-chevron-down {
      transition: .3s transform ease-in-out;
      transform: rotate(180deg);
    }
    /* Chrome, Safari, Edge, Opera */
    input::-webkit-outer-spin-button,
    input::-webkit-inner-spin-button {
      -webkit-appearance: none;
      margin: 0;
    }
    /* Firefox */
    input[type=number] {
      -moz-appearance: textfield;
    }
    @media (max-width: 767px) {
      .sidebar {
        width: 60px !important;
      }
      .sidebar .d-none {
        display: none !important;
      }
      .content {
        margin-left: 10px;
        padding-left: 5px;
      }
    }
    @media (min-width: 768px) and (max-width: 991px) and (orientation: portrait) {
      .sidebar {
        width: 80px !important;
        padding-right: 5px;
      }
      .sidebar .d-none {
        display: none !important;
      }
      .content {
        margin-left: 10px;
        padding-left: 5px;
      }
    }
    @media only screen 
      and (min-device-width: 768px) 
      and (max-device-width: 1024px) 
      and (orientation: landscape) {
      .sidebar {
        width: 200px !important;
      }
      .content {
        margin-left: 10px;
      }
    }
    .sidebar {
      transition: width 0.3s ease;
    }
    .content {
      transition: margin-left 0.3s ease;
    }
  </style>  
</head>
<body>
  <div class="container-fluid">
    <div class="row flex-nowrap">
      <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-secondary sidebar">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
          <img src="{% static 'img/simOrder_logo_white.svg' %}" alt="Logo" class="img-fluid mb-3 mt-3">
          <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start fs-5" id="menu-base">
            <li class="nav-item">
              <a href="{% url 'urlHome' %}" class="nav-link align-middle px-0 py-3 text-white">
                <i class="fa-solid fa-house"></i><span class="ms-2 d-none d-md-inline">{% trans 'Home' %}</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'urlOrders' %}" class="nav-link align-middle px-0 py-3 text-white">
                <i class="fa-solid fa-user-pen"></i><span class="ms-2 d-none d-md-inline">{% trans 'My Orders' %}</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'urlOrdersAll' %}" class="nav-link align-middle px-0 py-3 text-white">
                <i class="fa-solid fa-list-check"></i><span class="ms-2 d-none d-md-inline">{% trans 'All Orders' %}</span>
              </a>
            </li>
            {% if user.is_staff %}
            <li>
              <div class="dropdown pb-0 fs-5">
                <a href="#" class="nav-link px-0 py-3 text-white align-middle dropdown-toggle" id="dropdownAdmin" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-user-gear"></i><span class="ms-2 d-none d-md-inline">{% trans 'Admin' %}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownAdmin">
                  <li><a class="dropdown-item" href="{% url 'admin:custom_auth' %}">{% trans 'Users and Groups' %}</a></li>
                  <li><a class="dropdown-item" href="{% url 'admin:custom_simorder' %}">{% trans 'MasterData' %}</a></li>
                  <li><a class="dropdown-item" href="{% url 'urlAdminOrdersAll' %}">{% trans 'Analytics' %}</a></li>
                </ul>
              </div>
            </li>
            <li>
              <div class="dropdown pb-0 fs-5">
                <a href="#" class="nav-link px-0 py-3 text-white align-middle dropdown-toggle" id="dropdownSettings" data-bs-toggle="dropdown" aria-expanded="false">
                  <i class="fa-solid fa-wrench"></i><span class="ms-2 d-none d-md-inline">{% trans 'Settings' %}</span>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownSettings">
                  <li><a class="dropdown-item" href="{% url 'urlPrinters' %}">{% trans 'Printers' %}</a></li>
                  <li><a class="dropdown-item" href="{% url 'urlSettings' %}">{% trans 'System' %}</a></li>
                </ul>
              </div>
            </li>
            {% endif %}
            <li>
              {% if user.is_authenticated %}
              <form class="logout-form" id="logout-form" method="post" action="{% url 'logout' %}?next={% url 'login' %}">
                {% csrf_token %}
                <a href="#" class="nav-link px-0 py-3 text-white align-middle" onclick="document.getElementById('logout-form').submit()">
                  <i class="fa-solid fa-right-from-bracket"></i><span class="ms-2 d-none d-md-inline">{% trans 'Logout' %}</span>
                </a>
              </form>
              {% else %}
              <a href="{% url 'login' %}?next={{ urlHome }}" class="nav-link px-0 py-3 text-white align-middle">
                <i class="fa-solid fa-right-to-bracket"></i><span class="ms-2 d-none d-md-inline">{% trans 'Login' %}</span>
              </a>
              {% endif %}
            </li>
          </ul>
          <hr>
          <div class="dropdown pb-0 fs-5 mb-5">
            <a href="#" class="nav-link px-0 py-3 text-white align-middle dropdown-toggle" id="dropdownPower" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="fa-solid fa-power-off"></i><span class="ms-2 d-none d-md-inline">{% trans 'Power' %}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownPower">
              <li><a class="dropdown-item" href="{% url 'urlPower' 0 %}" onclick="return confirm ('You are about to shutdown the system. Are you sure?')">{% trans 'Shutdown' %}</a></li>
              <li><a class="dropdown-item" href="{% url 'urlPower' 1 %}" onclick="return confirm ('You are about to reboot the system. Are you sure?')">{% trans 'Reboot' %}</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col py-3 content">
        {% if user.is_authenticated %}
          <h4 class="text-secondary">{% trans 'Welcome to simOrder' %},<span style="color:#FF7F50;">&nbsp;{{ user.get_username }}</span></h4>
        {% else %}
          <h4 class="text-secondary">{% trans 'simOrder: please login' %}</h4>
          <hr class="mt-0 mb-4">
        {% endif %}
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

simorder/templates/bootstrap.html
{% extends 'django_bootstrap5/bootstrap5.html' %}

{% block bootstrap5_title %}{% block title %}{% endblock %}{% endblock %}

simorder/templates/index.html
{% extends 'base.html' %}
{% load i18n static custom_tags %}

{% block title %} {% trans 'simOrder: Home' %} {% endblock %}

{% block content %}
<h3>{% trans 'Getting started:' %}</h3>

<div class="row">
    <div class="list-group list-group-flush list-group-numbered">
        <a href="{% url 'urlSettings' %}" class="list-group-item list-group-item-action">{% trans "Fill-in your company data and basic information" %}</a>
        <a href="{% url 'urlPrinters' %}" class="list-group-item list-group-item-action">{% trans "Install a USB or Bluetooth printer" %}</a>
        <a href="{% url 'admin:custom_simorder' %}" class="list-group-item list-group-item-action">{% trans "Create your Product Classes, Products and Menus" %}</a>
        <a href="{% url 'admin:custom_auth' %}" class="list-group-item list-group-item-action">{% trans "If necessary, create and manage Users and/ or Groups" %}</a>
        <a href="{% url 'urlOrders' %}" class="list-group-item list-group-item-action">{% trans "Create and manage Orders" %}</a>
        <a class="list-group-item list-group-item-action">{% trans "Enjoy using simOrder !" %}</a>
    </div>
</div>

{% endblock content %}

simorder/templates/orders_all.html
{% extends 'base.html' %}
{% load i18n static custom_tags %}

{% block title %} {% trans 'simOrder: All Orders' %} {% endblock %}

{% block content %}
<h3>{% trans 'All orders' %}</h3>

{% if filter.qs %}
<form method="get" class="form-inline my-2 my-lg-0">
{% csrf_token %}
<!-- FILTER AREA -->
<div class="row align-items-end">
    <div class="col-md-3 mt-1 mb-1">
        <label for="{{ filter.form.orderUser.auto_id }}" class="form-label">{% trans 'User:' %}</label>
        <select class="form-select" name="{{ filter.form.orderUser.name }}" id="{{ filter.form.orderUser.auto_id }}" aria-label="Default select example">
            {% for value, text in filter.form.fields.orderUser.choices %}
            <option value="{{ value }}">{{ text }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="col-md-3 mt-1 mb-1">
        <label for="{{ filter.form.orderDtClose__gt.auto_id }}" class="form-label">{% trans 'Date from:' %}</label>
        <input type="date" class="form-control datetimepicker-input" name="{{ filter.form.orderDtClose__gt.name }}" id="{{ filter.form.orderDtClose__gt.auto_id }}" value="{{ filter.form.orderDtClose__gt.value }}"/>
    </div>    
    <div class="col-md-3 mt-1 mb-1">
        <label for="{{ filter.form.orderStatus.auto_id }}" class="form-label">{% trans 'Status:' %}</label>
        <select class="form-select" name="{{ filter.form.orderStatus.name }}" id="{{ filter.form.orderStatus.auto_id }}" aria-label="Default select example">
            <option value="unknown">{% trans 'All' %}</option>
            <option value="0">{% trans 'Open' %}</option>
            <option value="1">{% trans 'Closed' %}</option>
        </select>
    </div>
    <div class="col-md-3 mt-1 mb-1">
        <button class="btn btn-outline-secondary" type="submit"><i class="fa-solid fa-magnifying-glass me-2"></i>{% trans 'Search' %}</button>
    </div>
</div>
</form>
<!-- Messages -->
{% if messages %}
{% for message in messages %}
<div class="row mt-3">
    <div class="col">
        {% if message.tags == "success" %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
            <i class="fa-solid fa-circle-check"></i>&nbsp;&nbsp;{{ message }}
        {% elif message.tags == "warning" %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <i class="fa-solid fa-circle-exclamation"></i>&nbsp;&nbsp;{{ message }}
        {% elif message.tags == "error" %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <i class="fa-solid fa-circle-xmark"></i>&nbsp;&nbsp;{{ message }}
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{% trans 'Close' %}"></button></div>
    </div>
</div>
{% endfor %}
{% endif %}
<!-- COLLAPSIBLE TABLE -->
<div class="table-responsive">
    <table class="table table-hover">
    <thead>
        <tr>            
            <th>{% trans 'Table' %}</th>
            <th>{% trans 'Order' %}</th>
            <th>{% trans 'Actions' %}</th>
            <th>{% trans 'User' %}</th>
            <th>{% trans 'Date' %}</th>
            <th>{% trans 'Total Time' %}</th>
            <th>{% trans 'Status' %}</th>
            <th>{% trans 'Menu' %}</th>
            <th>{% trans 'Total' %}</th>
            <th>{% trans 'Products' %}</th>
            <th></th>
        </tr> 
    </thead>
    <tbody>
        {% for order in filter.qs %}
        <tr>
            {% if order.orderStatus == 1 %}
            <td>{{ order.orderTable }}</a></td>
            {% else %}
            <td><a href="/orders/update/{{ order.id }}">{{ order.orderTable }}</a></td>
            {% endif %}
            <td>{{ order.id }}</td>
            <td>
                <div class="btn-group flex-wrap">
                {% if order.orderStatus == 1 %}
                <a type="button" class="btn btn-link" title="Update"><span style="color: grey;"><i class="fa-solid fa-pen"></span></i></a>
                <a type="button" class="btn btn-link" title="Close"><span style="color: grey;"><i class="fa-solid fa-dollar-sign"></span></i></a>
                    {% if user.is_staff %}
                    <a type="button" class="btn btn-link" title="Delete" href="/orders/delete/{{ order.id }}" onclick="return confirm('{% trans 'Order will be permanentely deleted. Are you sure?' %}')">
                        <span style="color: red;"><i class="fa-solid fa-trash"></span></i></a>
                    {% endif %}
                {% else %}
                <a type="button" class="btn btn-link" title="Update" href="/orders/update/{{ order.id }}"><span style="color: orange;"><i class="fa-solid fa-pen"></span></i></a>
                <a type="button" class="btn btn-link" title="Close" href="/orders/close/{{ order.id }}"><span style="color: green;"><i class="fa-solid fa-dollar-sign"></span></i></a>
                    {% if user.is_staff %}
                    <a type="button" class="btn btn-link" title="Delete" href="/orders/delete/{{ order.id }}" onclick="return confirm('{% trans 'Order will be permanentely deleted. Are you sure?' %}')">
                        <span style="color: red;"><i class="fa-solid fa-trash"></span></i></a>
                    {% endif %}
                {% endif %}
                </div>
            </td>
            <td>{{ order.orderUser.username }}</td>
            <td>{{ order.orderDtClose|date:"D d.m.Y" }}</td>
            <td>{{ order.orderDtOpen|timesince:order.orderDtClose }}</td>
            {% if order.orderStatus == 1 %}
            <td><span style="color: green;"><i class="fa-regular fa-lock"></span></i></td> 
            {% else %}
            <td><span style="color: red;"><i class="fa-solid fa-lock-open"></span></i></td>     
            {% endif %}
            <td>{{ order.menuQuery.menuDescription }}</td>
            <td>{{ order.get_total_order|floatformat:2 }}</td>
            <td><a type="button" class="btn btn-secondary btn-sm" title="List of Products" data-bs-toggle="collapse" data-bs-target=".table{{order.id}}" aria-expanded="false">
                <i class="fa-solid fa-chevron-down"></i></td>
        </tr>

        <tr class="collapse table{{order.id}}">
            <td colspan="999">
            <div>
            <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans 'Product' %}</th>
                    <th>{% trans 'Price' %}</th>
                    <th>{% trans 'Status' %}</th>
                    <th>{% trans 'Transaction Number' %}</th>
                    <th>{% trans 'Actions' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for prod in order.productorder_set.all %}
                    {% if prod.poStatus != 2 %}
                    <tr>
                        <!--<td>{{ prod.id }}</td>-->
                        <td>{{ prod.poProdDescription }}</td>
                        <td>{{ prod.poProdPrice }}</td>
                        {% if prod.poStatus == 0 %}
                        <td><span style="color: red;"><i class="fa-solid fa-lock-open"></i></span></i></td>
                        {% elif prod.poStatus == 1 %}
                        <td><span style="color: green;"><i class="fa-regular fa-lock"></span></i></td>     
                        {% endif %}
                        <td>{{ prod.poTransNumber }}</td>
                        <td>
                        {% if prod.poTransNumber %}
                            <a type="button" class="btn btn-link" title="Reprint" href="{% url 'urlReprintOrder' order.id prod.poTransNumber %}">
                            <span style="color:#FF7F50;"><i class="fa-solid fa-print"></span></i></a>
                        {% endif %}
                        {% if user.is_staff %}
                            <a type="button" class="btn btn-link" title="Delete" href="{% url 'urlDeleteOrderProduct' prod.id %}" onclick="return confirm('{% trans 'Product will be permanentely removed. Are you sure?' %}')">
                            <span style="color: red;"><i class="fa-solid fa-trash"></span></i></a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            </tbody>
            </table>
            </div>
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
    <p class="text-danger">{% trans 'No orders found.' %}</p>
{% endif %}

{% endblock content %}

simorder/templates/power.html
{% extends 'base.html' %}
{% load i18n static custom_tags %}

{% block title %} {% trans 'simOrder: Power' %} {% endblock %}

{% block content %}

<div id="shutdown-status">
    <h3>{{ message }}</h3>
    <div class="spinner-border" style="width: 3rem; height: 3rem;" role="status">
        <span class="visually-hidden">{% trans 'Loading...' %}</span>
    </div>
</div>

<div id="shutdown-message" style="display: none;">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {% if op_id == 0 %}
        <i class="fa-solid fa-circle-check me-2"></i>{% trans 'You can now shut down your Pi.' %}
        {% else %}
        {% url 'urlHome' as home_url %}
        {% blocktrans %}
        <i class="fa-solid fa-circle-check me-2"></i>Restart in process. Go to <a href="{{ home_url }}">Home</a> after some seconds.
        {% endblocktrans %}
        {% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="{% trans 'Close' %}"></button>
    </div>
</div>

<script>
    function checkPowerStatus() {
        Promise.all([
            fetch('/power/0'),
            fetch('/power/1')
        ])
        .then(responses => {
            if (responses.every(response => response.ok)) {
                console.log("Both power endpoints are responding");
            } else {
                console.log("At least one power endpoint is not responding");
                document.getElementById('shutdown-status').style.display = 'none';
                document.getElementById('shutdown-message').style.display = 'block';
            }
        })
        .catch(() => {
            console.log("Error occurred while checking power status");
            document.getElementById('shutdown-status').style.display = 'none';
            document.getElementById('shutdown-message').style.display = 'block';
        });
    }

    checkPowerStatus();
    setInterval(checkPowerStatus, 5000);
</script>
{% endblock content %}